// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEt_DjSwFP4eSaR5K5AaoeU-K5-w9fLM',
    appId: '1:634396483295:web:dee48ef80c5657c0cc136a',
    messagingSenderId: '634396483295',
    projectId: 'viroomall-marketplace',
    authDomain: 'viroomall-marketplace.firebaseapp.com',
    storageBucket: 'viroomall-marketplace.firebasestorage.app',
    measurementId: 'G-4P5SYKWLP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUk9mLpkz8LWtRX5wyfwl8AlgKZVDiiNk',
    appId: '1:634396483295:android:995a299ed2ac5752cc136a',
    messagingSenderId: '634396483295',
    projectId: 'viroomall-marketplace',
    storageBucket: 'viroomall-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwPNGdo8XeE37RNUHaqc2vFKEVkNvj0Q',
    appId: '1:634396483295:ios:f4a1b403a0f5b87ccc136a',
    messagingSenderId: '634396483295',
    projectId: 'viroomall-marketplace',
    storageBucket: 'viroomall-marketplace.firebasestorage.app',
    iosBundleId: 'com.viroomall.viroomallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwPNGdo8XeE37RNUHaqc2vFKEVkNvj0Q',
    appId: '1:634396483295:ios:f4a1b403a0f5b87ccc136a',
    messagingSenderId: '634396483295',
    projectId: 'viroomall-marketplace',
    storageBucket: 'viroomall-marketplace.firebasestorage.app',
    iosBundleId: 'com.viroomall.viroomallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOEt_DjSwFP4eSaR5K5AaoeU-K5-w9fLM',
    appId: '1:634396483295:web:2cda1e8b2dc3e038cc136a',
    messagingSenderId: '634396483295',
    projectId: 'viroomall-marketplace',
    authDomain: 'viroomall-marketplace.firebaseapp.com',
    storageBucket: 'viroomall-marketplace.firebasestorage.app',
    measurementId: 'G-TKKRRFZ4Z8',
  );
}
